"""Public CLI API."""

from __future__ import annotations

from cli.handlers import (
    handle_actions,
    handle_build_prompt_jepa_index,
    handle_build_transition_evidence_bundle,
    handle_change,
    handle_compare_diagnostics,
    handle_decide_transition_guarded_trial,
    handle_demo_prompt_jepa,
    handle_demo_transition_bench,
    handle_eval,
    handle_evaluate_transition_shadow_scorer,
    handle_fix,
    handle_greenshot_7,
    handle_implement,
    handle_inspect_prompt_corpus,
    handle_inspect_transition_assets,
    handle_mine,
    handle_normalize_transition_shadow_outcomes,
    handle_patch,
    handle_query_prompt_jepa_index,
    handle_report_transition_residuals,
    handle_run_transition_shadow_matrix,
    handle_run_transition_shadow_suite,
    handle_summarize_transition_advice,
    handle_train,
    handle_train_prompt_intents,
    handle_train_ranker,
    handle_validate_prompt_corpus,
)
from cli.main import main
from cli.parser import build_parser

__all__ = [
    "build_parser",
    "handle_actions",
    "handle_build_prompt_jepa_index",
    "handle_build_transition_evidence_bundle",
    "handle_change",
    "handle_compare_diagnostics",
    "handle_decide_transition_guarded_trial",
    "handle_demo_prompt_jepa",
    "handle_demo_transition_bench",
    "handle_eval",
    "handle_evaluate_transition_shadow_scorer",
    "handle_fix",
    "handle_greenshot_7",
    "handle_implement",
    "handle_inspect_prompt_corpus",
    "handle_inspect_transition_assets",
    "handle_mine",
    "handle_normalize_transition_shadow_outcomes",
    "handle_patch",
    "handle_query_prompt_jepa_index",
    "handle_report_transition_residuals",
    "handle_run_transition_shadow_matrix",
    "handle_run_transition_shadow_suite",
    "handle_summarize_transition_advice",
    "handle_train",
    "handle_train_prompt_intents",
    "handle_train_ranker",
    "handle_validate_prompt_corpus",
    "main",
]
